reset_cluster: False

openshift_clients:
  'v3.6':
    url: https://github.com/openshift/origin/releases/download/v3.6.0
    release_ver: openshift-origin-client-tools-v3.6.0-c4dd4cf
  'v3.7':
    url: https://github.com/openshift/origin/releases/download/v3.7.0
    release_ver: openshift-origin-client-tools-v3.7.0-7ed6862
  'v3.9':
    url: https://github.com/openshift/origin/releases/download/v3.9.0
    release_ver: openshift-origin-client-tools-v3.9.0-191fece
  'v3.10':
    url: https://github.com/openshift/origin/releases/download/v3.10.0
    release_ver: openshift-origin-client-tools-v3.10.0-dd10d17
  'v3.11':
    url: https://github.com/openshift/origin/releases/download/v3.11.0
    release_ver: openshift-origin-client-tools-v3.11.0-0cbc58b
  'v4.0':
    url: https://apb-oc.s3.amazonaws.com/apb-oc
    release_ver: oc
  'latest':
    url: https://apb-oc.s3.amazonaws.com/apb-oc
    release_ver: oc

openshift_client_version: "{{ origin_image_tag }}"
oc_tools_dir: /usr/local/bin

# Temporary fix until release version of oc client works with latest images.
openshift_client_url: https://s3.amazonaws.com/catasb/linux/amd64/oc
